name: design_system
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  masterclass_app:
    path: ../app

  font_awesome_flutter: ^10.5.0

  flutter_modular: ^5.0.3

  google_fonts: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/masterclass.png 
    - assets/dev_picture.png